## 결측값 처리
- 완전제거법
- 수작업
- 특정값
- 핫덱 대체법
    - 동일한 조사, 다른 관측값으로 대체
    - 결측치와 비슷한 특성을 가진 것을 무작위 추출하여 대체
- 평균값
    - 표준오차 과소추정 발생
- 가장 가능성이 높은 값 사용 (회귀분석, 보간법 등)

## 데이터 인코딩
- 레이블 인코딩
- 원-핫 인코딩

### 레이블 인코딩
- 범주형 자료의 수치화
- LabelEncoder
- fit()
- transform()

In [2]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(labels)

[0 1 4 5 3 3 2 2]


In [3]:
# 인코딩 전 원래값
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [4]:
# 디코딩
encoder.inverse_transform(labels)

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

### 원-핫 인코딩
- 고유 값에 해당하는 column에만 1을 주고 나머지는 0
- OneHotEncoder
- 회귀분석의 경우 dummy 변수로 변환

In [9]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# 1. 문자열을 숫자형으로 변환해야함 (사실 불필요함)
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

In [10]:
# 2. 2차원 데이터로 변환 **필수**
labels = labels.reshape(-1, 1)

encoder = OneHotEncoder()
encoder.fit(labels)
labels = encoder.transform(labels)
print(labels)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 4)	1.0
  (3, 5)	1.0
  (4, 3)	1.0
  (5, 3)	1.0
  (6, 2)	1.0
  (7, 2)	1.0


In [11]:
# array로 변환
labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [12]:
# sparse=False : 처음부터 array로 반환
items_arr = np.array(items)
items_arr = items_arr.reshape(-1, 1)

encoder = OneHotEncoder(sparse=False)
encoder.fit(items_arr)
labels = encoder.transform(items_arr)
print(labels)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


### Pandas get_dummies() 메서드 이용

In [14]:
import pandas as pd

items_df = pd.DataFrame({'item':items})
items_df

item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [15]:
pd.get_dummies(items_df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

In [17]:
# array로 변환
pd.get_dummies(items_df).to_numpy()

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]], dtype=uint8)

## Feature Scaling
- 가능하다면 전체 데이터를 스케일링 후 split
- Z-scaling
    - 표준화 : 평균이 0, 분산이 1
    - `StandardScaler`
- Min-max
    - 0~1로 변환
    - `MinMaxScaler`
- 벡터 정규화
    - `Nomalizer`

#### - Max Absolute Scaling : $ \frac {X} { |X_{max}|}$

#### - Robust Scaling : $ \frac {X-X_{2/4}} { X_{3/4}-X_{1/4}}$

In [19]:
from sklearn.datasets import load_iris

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(iris_data, columns=iris.feature_names)

In [20]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [21]:
iris_df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [33]:
# 표준화를 직접 시행
mean = iris_df.mean()
std = iris_df.std(ddof=0)

iris_std = ( iris_df - mean ) / std

In [34]:
iris_std

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
1            -1.143017         -0.131979          -1.340227         -1.315444
2            -1.385353          0.328414          -1.397064         -1.315444
3            -1.506521          0.098217          -1.283389         -1.315444
4            -1.021849          1.249201          -1.340227         -1.315444
..                 ...               ...                ...               ...
145           1.038005         -0.131979           0.819596          1.448832
146           0.553333         -1.282963           0.705921          0.922303
147           0.795669         -0.131979           0.819596          1.053935
148           0.432165          0.788808           0.933271          1.448832
149           0.068662         -0.131979           0.762758          0.790671

[150 rows x 4 columns]

In [35]:
iris_std.describe().round(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count            150.000           150.000            150.000   
mean              -0.000            -0.000             -0.000   
std                1.003             1.003              1.003   
min               -1.870            -2.434             -1.568   
25%               -0.901            -0.592             -1.227   
50%               -0.053            -0.132              0.336   
75%                0.675             0.559              0.763   
max                2.492             3.091              1.786   

       petal width (cm)  
count           150.000  
mean             -0.000  
std               1.003  
min              -1.447  
25%              -1.184  
50%               0.133  
75%               0.791  
max               1.712

### 표준화

In [30]:
# StandardScaler 이용
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_scaled = pd.DataFrame(iris_scaled, columns=iris.feature_names)
iris_scaled

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
1            -1.143017         -0.131979          -1.340227         -1.315444
2            -1.385353          0.328414          -1.397064         -1.315444
3            -1.506521          0.098217          -1.283389         -1.315444
4            -1.021849          1.249201          -1.340227         -1.315444
..                 ...               ...                ...               ...
145           1.038005         -0.131979           0.819596          1.448832
146           0.553333         -1.282963           0.705921          0.922303
147           0.795669         -0.131979           0.819596          1.053935
148           0.432165          0.788808           0.933271          1.448832
149           0.068662         -0.131979           0.762758          0.790671

[150 rows x 4 columns]

In [32]:
iris_scaled.describe().round(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count            150.000           150.000            150.000   
mean              -0.000            -0.000             -0.000   
std                1.003             1.003              1.003   
min               -1.870            -2.434             -1.568   
25%               -0.901            -0.592             -1.227   
50%               -0.053            -0.132              0.336   
75%                0.675             0.559              0.763   
max                2.492             3.091              1.786   

       petal width (cm)  
count           150.000  
mean             -0.000  
std               1.003  
min              -1.447  
25%              -1.184  
50%               0.133  
75%               0.791  
max               1.712

### Minmax

In [36]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_scaled = pd.DataFrame(iris_scaled, columns=iris.feature_names)
iris_scaled

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             0.222222          0.625000           0.067797          0.041667
1             0.166667          0.416667           0.067797          0.041667
2             0.111111          0.500000           0.050847          0.041667
3             0.083333          0.458333           0.084746          0.041667
4             0.194444          0.666667           0.067797          0.041667
..                 ...               ...                ...               ...
145           0.666667          0.416667           0.711864          0.916667
146           0.555556          0.208333           0.677966          0.750000
147           0.611111          0.416667           0.711864          0.791667
148           0.527778          0.583333           0.745763          0.916667
149           0.444444          0.416667           0.694915          0.708333

[150 rows x 4 columns]

In [37]:
iris_scaled.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            0.428704          0.440556           0.467458   
std             0.230018          0.181611           0.299203   
min             0.000000          0.000000           0.000000   
25%             0.222222          0.333333           0.101695   
50%             0.416667          0.416667           0.567797   
75%             0.583333          0.541667           0.694915   
max             1.000000          1.000000           1.000000   

       petal width (cm)  
count        150.000000  
mean           0.458056  
std            0.317599  
min            0.000000  
25%            0.083333  
50%            0.500000  
75%            0.708333  
max            1.000000

### 기울어져 있는(비대칭) 분포
- Positively Skewed (오른쪽으로 꼬리가 긴 분포)
    - 값이 큰 것들을 작게 변환
    - $\sqrt x$
    - $\log x$
    - $1/x$
- Negatively Skewed (왼쪽으로 꼬리가 긴 분포)
    - $\sqrt {\max(x+1)-x}$
    - $\log (\max(x+1)-x)$
    - $1/(\max(x+1)-x)$