In [1]:
import numpy as np

X = np.array([[3, 1, 2],[2, 6, -1],[4, 0, -1]])
y = np.array([5, 1, 3])

In [2]:
X, y

(array([[ 3,  1,  2],
        [ 2,  6, -1],
        [ 4,  0, -1]]),
 array([5, 1, 3]))

1. 1행 1열을 1로 만들기
2. 2행에 1행\*2행 1열을 빼서 2행 1열을 0으로 만들기
3. 2행 2열을 1로 만들기
4. 3행에 1행\*3행 1열과 2행\*3행 2열을 빼서 3행 1, 2열을 0으로 만들기
5. n행 n열이 1이 될 때까지 반복
6. 끝에서부터 차례대로 x값 계산  
※ k행 k열이 0인 경우는 생각되지 않음 (원래는 행 스위치 필요 및 determinant가 0이 아닐 때만 사용)

In [3]:
def solve(A, b):
    """
    연립 방정식 풀기
    입력값: 솔루션을 구하고 싶은 A, b
    출력값: 방정식의 솔루션 sol
    """
    import copy
    
    X = copy.deepcopy(A)
    sol = copy.deepcopy(b)
    n = len(X)

    for i in range(0,n):
        x_row = X[i]
        y_val = sol[i]

        if x_row[i]!=0:
            tmp = 1/x_row[i]
        else:
            tmp = 0

        x_row = [element * tmp for element in x_row]
        y_val = y_val*tmp

        X[i] = x_row
        sol[i] = y_val

        for j in range(0,n):
            if i==j:
                continue
            x_next = X[j]
            y_next = sol[j]
            x_tmp = [element * -x_next[i] for element in x_row]
            y_tmp = y_val*(-x_next[i])

            for k in range(0, len(x_row)):
                x_next[k] = x_tmp[k] + x_next[k]
            y_next = y_tmp + y_next

            X[j] = x_next
            sol[j] = y_next

    return sol

In [4]:
solve(X, y)

array([1, 0, 1])

In [5]:
np.linalg.inv(X) @ y

array([ 1.00000000e+00, -2.77555756e-17,  1.00000000e+00])

In [6]:
np.linalg.solve(X, y)

array([1., 0., 1.])