In [1]:
def det_rec(A):
    """
    Paramters
    ---------
    A: n x n 행렬 (list 또는 numpy ndarray)
    
    
    Returns
    -------
    determenant of A (float)
    """
    
    nrows = len(A)
    ncols = len(A[0])
    
    assert nrows == ncols, f'nrows ({nrows}) != ncols ({ncols})'
    
    import copy
    
    A = copy.deepcopy(A)
    if isinstance(A, np.ndarray):
        A = A.tolist()
    
    if nrows == 2:
        return A[0][0] * A[1][1] - A[0][1] * A[1][0]
    
    
    det = 0
    for i in range(ncols):
        sgn = (-1) ** (i%2)
        Aii = [A[j][0:i] + A[j][i+1:] for j in range(1, ncols)]
        det += sgn * A[0][i] * det_rec(Aii)
        
    return det

In [2]:
import numpy as np

In [3]:
A = np.array([[3,2,0], [-1,-3,6], [2,3,-5]])
B = [[3, 4], [1, 2]]
C = [[1,3,1,4], [3,9,5,15], [0,2,1,1],[0,4,2,3]]

$M_{ij}=det(A_{ij})$, minor determinant  
$C_{ij} = (-1)^{i+j}M_{ij}$, cofactor  
$\text{adj}(A) = C^T$, adjoint matrix  
$A^{-1} = \frac{1}{\det(A)}\text{adj}(A)$

In [4]:
def Cofactor(A):
    """
    A: 3 x 3 이상인 행렬
    """
    import copy
    
    A = copy.deepcopy(A)
    if isinstance(A, np.ndarray):
        A = A.tolist()
    
    nrows = len(A)
    ncols = len(A[0])
        
    C = []
    
    for i in range(nrows):
        Ci = []
        for j in range(ncols):
            Aij = [A[k][:j] + A[k][j+1:] for k in range(nrows) if k != i]
            Cij = (-1)**(i+j) * det_rec(Aij)
            
            Ci.append(Cij)
        
        C.append(Ci)
    
    return C

In [5]:
Co = Cofactor(A)
Co

[[-3, 7, 3], [10, -15, -5], [12, -18, -7]]

In [6]:
def transpose(A):
    """
    A^T
    """
    import copy
    
    A = copy.deepcopy(A)
    if isinstance(A, np.ndarray):
        A = A.tolist()

    nrows = len(A)
    ncols = len(A[0])
    
    AT = []
    for j in range(ncols):
        AT_row = []
        
        for i in range(nrows):
            AT_row.append(A[i][j])
            
        AT.append(AT_row)
        
    return AT

In [7]:
T = transpose(Co)
T

[[-3, 10, 12], [7, -15, -18], [3, -5, -7]]

In [8]:
def inv(A):
    import copy
    
    A = copy.deepcopy(A)
    if isinstance(A, np.ndarray):
        A = A.tolist()
    
    nrows = len(A)
    ncols = len(A[0])
    
    if nrows == 2:
        det = det_rec(A)
        return [[A[1][1] / det, -A[0][1] / det], [-A[1][0] / det, A[0][0] / det]]
    
    det = det_rec(A)
    
    assert det != 0, "det(A) != 0"
    
    adjA = transpose(Cofactor(A))
    
    invA = []
    for i in range(nrows):
        row = []
        for j in range(ncols):
            row.append(adjA[i][j] / det)
            
        invA.append(row)
        
    return invA

In [9]:
inv(A)

[[-0.6, 2.0, 2.4], [1.4, -3.0, -3.6], [0.6, -1.0, -1.4]]

In [10]:
np.linalg.inv(A)

array([[-0.6,  2. ,  2.4],
       [ 1.4, -3. , -3.6],
       [ 0.6, -1. , -1.4]])

In [11]:
inv(B)

[[1.0, -2.0], [-0.5, 1.5]]

In [12]:
np.linalg.inv(B)

array([[ 1. , -2. ],
       [-0.5,  1.5]])

In [13]:
inv(C)

[[0.25, 0.25, 5.0, -3.25],
 [0.75, -0.25, -0.0, 0.25],
 [-1.5, 0.5, 3.0, -1.5],
 [-0.0, -0.0, -2.0, 1.0]]

In [14]:
np.linalg.inv(C)

array([[ 2.5000000e-01,  2.5000000e-01,  5.0000000e+00, -3.2500000e+00],
       [ 7.5000000e-01, -2.5000000e-01, -4.4408921e-16,  2.5000000e-01],
       [-1.5000000e+00,  5.0000000e-01,  3.0000000e+00, -1.5000000e+00],
       [-0.0000000e+00, -0.0000000e+00, -2.0000000e+00,  1.0000000e+00]])

In [15]:
X = np.array([[3, 1, 2],[2, 6, -1],[4, 0, -1]])
y = np.array([5, 1, 3])

In [19]:
def multiple_matrix(A, b):
    """
    A: m x n matrix
    b: n x k matrix
    """
    import copy
    
    X = copy.deepcopy(A)
    y = copy.deepcopy(b)
    
    if isinstance(X, np.ndarray):
        X = X.tolist()
    
    if isinstance(y, np.ndarray):
        y = y.tolist()
        
    ncols = len(X[0])
    nrows = len(y)
    
    assert ncols == nrows
    
    Z = []
    
    if not isinstance(y[0], list): # k = 1
        for row in X:
            element = 0
            for j in range(ncols):
                element += row[j] * y[j]
            
            Z.append(element)
        
        return Z
    
    
    for i, row in enumerate(X):
        zrow = []
        for k in range(len(y[0])):
            element = 0
            
            for j in range(ncols):
                element += row[j] * y[j][k]
                
            zrow.append(element)
            
        Z.append(zrow)
        
    return Z

In [23]:
def solve(A, b):
    """
    연립 방정식 풀기
    입력값: 솔루션을 구하고 싶은 A, b
    출력값: 방정식의 솔루션 sol
    """
    Ainv = inv(A)
    
    return multiple_matrix(Ainv, b)

In [24]:
solve(X, y)

[1.0, 0.0, 1.0000000000000002]

In [25]:
np.linalg.solve(X, y)

array([1., 0., 1.])