# 데이터 표현 방법

In [1]:
import torch

In [2]:
import numpy as np

In [3]:
a = torch.arange(3)
a

tensor([0, 1, 2])

In [4]:
type(a)

torch.Tensor

In [5]:
a.shape

torch.Size([3])

In [6]:
a.ndimension() # 차원 확인

1

# Array와 Tensor 처리

In [7]:
b = torch.tensor([1,2,3])
b

tensor([1, 2, 3])

In [8]:
c = torch.tensor(((1, 2), (3, 4)))

In [9]:
c

tensor([[1, 2],
        [3, 4]])

In [10]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
d = torch.tensor(arr)
d

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [11]:
d.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.array(d)

array([[1, 2, 3],
       [4, 5, 6]])

# 기본 연산

In [13]:
a = torch.tensor(20)
b = torch.tensor(10)

In [14]:
c = a + b
d = a - b
e = a * b
f = a / b

c, d, e, f

(tensor(30), tensor(10), tensor(200), tensor(2.))

In [15]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
a + b

tensor([5, 7, 9])

In [16]:
a * 3

tensor([3, 6, 9])

In [17]:
a + a

tensor([2, 4, 6])

In [23]:
# AutoGrad
x = torch.tensor(1.0, requires_grad=True) # AutoGrad 적용

In [24]:
a = x*3
y = a **2 # (3x)**2 = 9x**2 -> 미분하면 18x
y.backward() # 어떤 값에 대한 출력 tensor의 변화도를 전달 받고, 동일한 값에 대한 입력 tensor의 변화도를 계산

In [25]:
x.grad

tensor(18.)

In [27]:
x = torch.tensor(1.0, requires_grad=True)
a = x*3
a.backward()

x.grad

tensor(3.)